name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: bartoszmajkowski

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_REPO/ebiznesfront:latest ./frontend
          docker push $DOCKERHUB_REPO/ebiznesfront:latest

      - name: Build and push backend
        run: |
          docker build -t $DOCKERHUB_REPO/ebiznesback:latest ./backend
          docker push $DOCKERHUB_REPO/ebiznesback:latest
